# Generated by Django 3.2.9 on 2021-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=32, unique=True)),
                ('cname', models.CharField(max_length=32)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=32)),
                ('student_gender', models.CharField(default='', max_length=32)),
                ('student_birth', models.CharField(default='', max_length=32)),
                ('student_sdept', models.CharField(default='', max_length=32)),
                ('student_age', models.IntegerField(null=True)),
            ],
        ),
    ]
