# Generated by Django 3.2.9 on 2021-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32)),
                ('cno', models.CharField(max_length=32)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
